const locationData = {
    "台灣": {
        "台北市": { longitude: 121.5 },
        "台中市": { longitude: 120.9 },
        "新北市": { longitude: 121.5 },
        "桃園市": { longitude: 121.2 },
        "基隆市": { longitude: 121.7 },
        "新竹": { longitude: 121.1 },
        "苗栗": { longitude: 120.9 },
        "彰化": { longitude: 120.5 },
        "南投": { longitude: 120.7 },
        "雲林": { longitude: 120.4 },
        "嘉義": { longitude: 120.4 },
        "台南市": { longitude: 120.5 },
        "高雄市": { longitude: 120.5 },
        "屏東": { longitude: 120.2 },
        "宜蘭": { longitude: 121.3 },
        "花蓮": { longitude: 121.1 },
        "台東": { longitude: 121.0 },
        "澎湖": { longitude: 119.6 },
        "金門": { longitude: 118.6 },
        "連江": { longitude: 120.0 }
    },
    "北京市": { "北京市": { longitude: 116.4 } },
    "天津市": { "天津市": { longitude: 117.2 } },
    "河北省": {
        "石家庄市": { longitude: 114.5 },
        "唐山市": { longitude: 118.2 },
        "秦皇岛市": { longitude: 119.6 },
        "邯郸市": { longitude: 114.5 },
        "邢台市": { longitude: 114.5 },
        "保定市": { longitude: 115.5 },
        "张家口市": { longitude: 114.9 },
        "承德市": { longitude: 117.9 },
        "沧州市": { longitude: 116.8 },
        "廊坊市": { longitude: 116.7 },
        "衡水市": { longitude: 115.7 }
    },
    "山西省": {
        "太原市": { longitude: 112.5 },
        "大同市": { longitude: 113.3 },
        "阳泉市": { longitude: 113.6 },
        "长治市": { longitude: 113.1 },
        "晋城市": { longitude: 112.8 },
        "朔州市": { longitude: 112.4 },
        "晋中市": { longitude: 112.7 },
        "运城市": { longitude: 111.0 },
        "忻州市": { longitude: 112.7 },
        "临汾市": { longitude: 111.5 },
        "吕梁市": { longitude: 111.1 }
    },
    "内蒙古自治区": {
        "呼和浩特市": { longitude: 111.7 },
        "包头市": { longitude: 110.0 },
        "乌海市": { longitude: 118.3 },
        "赤峰市": { longitude: 118.9 },
        "通辽市": { longitude: 122.2 },
        "鄂尔多斯市": { longitude: 109.8 },
        "呼伦贝尔市": { longitude: 119.7 },
        "巴彦淖尔市": { longitude: 107.4 },
        "乌兰察布市": { longitude: 113.2 },
        "兴安盟": { longitude: 122.1 },
        "锡林郭勒盟": { longitude: 116.0 },
        "阿拉善盟": { longitude: 105.7 }
    },
    "辽宁省": {
        "沈阳市": { longitude: 123.4 },
        "大连市": { longitude: 121.6 },
        "鞍山市": { longitude: 122.9 },
        "抚顺市": { longitude: 123.9 },
        "本溪市": { longitude: 123.7 },
        "丹东市": { longitude: 124.3 },
        "锦州市": { longitude: 121.1 },
        "营口市": { longitude: 122.2 },
        "阜新市": { longitude: 121.6 },
        "辽阳市": { longitude: 123.2 },
        "盘锦市": { longitude: 122.0 },
        "铁岭市": { longitude: 123.8 },
        "朝阳市": { longitude: 120.4 },
        "葫芦岛市": { longitude: 120.8 }
    },
    "吉林省": {
        "长春市": { longitude: 125.3 },
        "吉林市": { longitude: 126.5 },
        "四平市": { longitude: 124.3 },
        "辽源市": { longitude: 125.1 },
        "通化市": { longitude: 125.9 },
        "白山市": { longitude: 126.4 },
        "松原市": { longitude: 124.8 },
        "白城市": { longitude: 122.8 },
        "延边朝鲜族自治州": { longitude: 129.5 }
    },
    "黑龙江省": {
        "哈尔滨市": { longitude: 126.6 },
        "齐齐哈尔市": { longitude: 123.9 },
        "鸡西市": { longitude: 130.9 },
        "鹤岗市": { longitude: 130.3 },
        "双鸭山市": { longitude: 131.1 },
        "大庆市": { longitude: 125.1 },
        "伊春市": { longitude: 129.0 },
        "佳木斯市": { longitude: 130.3 },
        "七台河市": { longitude: 130.9 },
        "牡丹江市": { longitude: 129.6 },
        "黑河市": { longitude: 127.5 },
        "绥化市": { longitude: 126.9 },
        "大兴安岭地区": { longitude: 124.7 }
    },
    "上海市": { "上海市": { longitude: 121.4 } },
    "江苏省": {
        "南京市": { longitude: 118.8 },
        "无锡市": { longitude: 120.3 },
        "徐州市": { longitude: 117.2 },
        "常州市": { longitude: 119.9 },
        "苏州市": { longitude: 120.6 },
        "南通市": { longitude: 120.8 },
        "连云港市": { longitude: 119.2 },
        "淮安市": { longitude: 119.0 },
        "盐城市": { longitude: 120.1 },
        "扬州市": { longitude: 119.4 },
        "镇江市": { longitude: 119.4 },
        "泰州市": { longitude: 119.9 },
        "宿迁市": { longitude: 118.3 }
    },
    "浙江省": {
        "杭州市": { longitude: 120.2 },
        "宁波市": { longitude: 121.5 },
        "温州市": { longitude: 120.6 },
        "嘉兴市": { longitude: 120.7 },
        "湖州市": { longitude: 120.1 },
        "绍兴市": { longitude: 120.5 },
        "金华市": { longitude: 119.6 },
        "衢州市": { longitude: 118.8 },
        "舟山市": { longitude: 122.3 },
        "台州市": { longitude: 121.4 },
        "丽水市": { longitude: 119.9 }
    },
    "安徽省": {
        "合肥市": { longitude: 117.3 },
        "芜湖市": { longitude: 118.3 },
        "蚌埠市": { longitude: 117.3 },
        "淮南市": { longitude: 116.7 },
        "马鞍山市": { longitude: 118.5 },
        "淮北市": { longitude: 116.8 },
        "铜陵市": { longitude: 117.8 },
        "安庆市": { longitude: 117.0 },
        "黄山市": { longitude: 118.3 },
        "滁州市": { longitude: 118.3 },
        "阜阳市": { longitude: 115.8 },
        "宿州市": { longitude: 116.9 },
        "六安市": { longitude: 116.5 },
        "亳州市": { longitude: 115.7 },
        "池州市": { longitude: 117.4 },
        "宣城市": { longitude: 118.7 }
    },
    "福建省": {
        "福州市": { longitude: 119.3 },
        "厦门市": { longitude: 118.1 },
        "莆田市": { longitude: 119.0 },
        "三明市": { longitude: 117.6 },
        "泉州市": { longitude: 118.6 },
        "漳州市": { longitude: 117.6 },
        "南平市": { longitude: 118.0 },
        "龙岩市": { longitude: 117.0 },
        "宁德市": { longitude: 119.5 }
    },
    "江西省": {
        "南昌市": { longitude: 115.9 },
        "景德镇市": { longitude: 117.2 },
        "萍乡市": { longitude: 113.8 },
        "九江市": { longitude: 116.0 },
        "新余市": { longitude: 114.9 },
        "鹰潭市": { longitude: 117.0 },
        "赣州市": { longitude: 114.9 },
        "宜春市": { longitude: 114.4 },
        "上饶市": { longitude: 117.9 },
        "吉安市": { longitude: 114.9 },
        "抚州市": { longitude: 116.3 }
    },
    "山东省": {
        "济南市": { longitude: 117.0 },
        "青岛市": { longitude: 120.3 },
        "淄博市": { longitude: 118.0 },
        "枣庄市": { longitude: 117.5 },
        "东营市": { longitude: 118.5 },
        "烟台市": { longitude: 121.4 },
        "潍坊市": { longitude: 119.1 },
        "济宁市": { longitude: 116.5 },
        "泰安市": { longitude: 117.1 },
        "威海市": { longitude: 122.1 },
        "日照市": { longitude: 119.5 },
        "滨州市": { longitude: 118.0 },
        "德州市": { longitude: 116.3 },
        "聊城市": { longitude: 115.9 },
        "临沂市": { longitude: 118.3 },
        "菏泽市": { longitude: 115.4 }
    },
    "河南省": {
        "郑州市": { longitude: 113.6 },
        "开封市": { longitude: 114.3 },
        "洛阳市": { longitude: 112.4 },
        "平顶山市": { longitude: 113.3 },
        "安阳市": { longitude: 114.3 },
        "鹤壁市": { longitude: 114.3 },
        "新乡市": { longitude: 113.9 },
        "焦作市": { longitude: 113.2 },
        "濮阳市": { longitude: 115.0 },
        "许昌市": { longitude: 113.8 },
        "漯河市": { longitude: 114.0 },
        "三门峡市": { longitude: 111.9 },
        "南阳市": { longitude: 112.5 },
        "商丘市": { longitude: 115.6 },
        "信阳市": { longitude: 114.0 },
        "周口市": { longitude: 114.6 },
        "驻马店市": { longitude: 114.0 },
        "济源市": { longitude: 112.6 }
    },
    "湖北省": {
        "武汉市": { longitude: 114.3 },
        "黄石市": { longitude: 114.9 },
        "十堰市": { longitude: 110.7 },
        "宜昌市": { longitude: 111.3 },
        "襄阳市": { longitude: 112.1 },
        "鄂州市": { longitude: 114.8 },
        "荆门市": { longitude: 112.2 },
        "孝感市": { longitude: 113.9 },
        "荆州市": { longitude: 112.2 },
        "黄冈市": { longitude: 114.8 },
        "咸宁市": { longitude: 114.3 },
        "随州市": { longitude: 113.3 },
        "恩施土家族苗族自治州": { longitude: 109.4 },
        "仙桃市": { longitude: 113.4 },
        "潜江市": { longitude: 112.9 },
        "天门市": { longitude: 113.1 },
        "神农架林区": { longitude: 110.3 }
    },
    "湖南省": {
        "长沙市": { longitude: 113.0 },
        "株洲市": { longitude: 113.1 },
        "湘潭市": { longitude: 112.9 },
        "衡阳市": { longitude: 112.6 },
        "邵阳市": { longitude: 111.4 },
        "岳阳市": { longitude: 113.1 },
        "常德市": { longitude: 111.6 },
        "张家界市": { longitude: 110.4 },
        "益阳市": { longitude: 112.3 },
        "郴州市": { longitude: 113.0 },
        "永州市": { longitude: 111.6 },
        "怀化市": { longitude: 110.0 },
        "娄底市": { longitude: 112.0 },
        "湘西土家族苗族自治州": { longitude: 109.7 }
    },
    "广东省": {
        "广州市": { longitude: 113.2 },
        "韶关市": { longitude: 113.6 },
        "深圳市": { longitude: 114.0 },
        "珠海市": { longitude: 113.5 },
        "汕头市": { longitude: 116.6 },
        "佛山市": { longitude: 113.1 },
        "江门市": { longitude: 113.0 },
        "湛江市": { longitude: 110.3 },
        "茂名市": { longitude: 110.8 },
        "肇庆市": { longitude: 112.4 },
        "惠州市": { longitude: 114.4 },
        "梅州市": { longitude: 116.1 },
        "汕尾市": { longitude: 115.3 },
        "河源市": { longitude: 114.6 },
        "阳江市": { longitude: 111.9 },
        "清远市": { longitude: 113.0 },
        "东莞市": { longitude: 113.7 },
        "中山市": { longitude: 113.3 },
        "潮州市": { longitude: 116.6 },
        "揭阳市": { longitude: 116.3 },
        "云浮市": { longitude: 112.0 }
    },
    "广西壮族自治区": {
        "南宁市": { longitude: 108.3 },
        "柳州市": { longitude: 109.4 },
        "桂林市": { longitude: 110.2 },
        "梧州市": { longitude: 111.3 },
        "北海市": { longitude: 109.1 },
        "防城港市": { longitude: 108.3 },
        "钦州市": { longitude: 108.6 },
        "贵港市": { longitude: 109.5 },
        "玉林市": { longitude: 110.1 },
        "百色市": { longitude: 106.6 },
        "贺州市": { longitude: 111.5 },
        "河池市": { longitude: 107.9 },
        "来宾市": { longitude: 109.2 },
        "崇左市": { longitude: 107.3 }
    },
    "海南省": {
        "海口市": { longitude: 110.3 },
        "三亚市": { longitude: 109.5 },
        "三沙市": { longitude: 112.3 },
        "儋州市": { longitude: 109.5 },
        "文昌市": { longitude: 110.7 },
        "琼海市": { longitude: 110.4 },
        "万宁市": { longitude: 110.4 },
        "五指山市": { longitude: 109.5 },
        "东方市": { longitude: 108.6 },
        "定安县": { longitude: 110.3 },
        "屯昌县": { longitude: 109.9 },
        "澄迈县": { longitude: 110.0 },
        "临高县": { longitude: 109.7 },
        "白沙黎族自治县": { longitude: 109.4 },
        "昌江黎族自治县": { longitude: 109.0 },
        "乐东黎族自治县": { longitude: 109.1 },
        "陵水黎族自治县": { longitude: 110.0 },
        "保亭黎族苗族自治县": { longitude: 109.7 },
        "琼中黎族苗族自治县": { longitude: 109.8 }
    },
    "重庆市": { "重庆市": { longitude: 106.5 } },
    "四川省": {
        "成都市": { longitude: 104.0 },
        "自贡市": { longitude: 104.7 },
        "攀枝花市": { longitude: 101.7 },
        "泸州市": { longitude: 105.4 },
        "德阳市": { longitude: 104.3 },
        "绵阳市": { longitude: 104.7 },
        "广元市": { longitude: 105.8 },
        "遂宁市": { longitude: 105.5 },
        "内江市": { longitude: 105.0 },
        "乐山市": { longitude: 103.7 },
        "南充市": { longitude: 106.1 },
        "眉山市": { longitude: 103.8 },
        "宜宾市": { longitude: 104.5 },
        "广安市": { longitude: 106.6 },
        "达州市": { longitude: 107.5 },
        "雅安市": { longitude: 103.0 },
        "巴中市": { longitude: 106.7 },
        "资阳市": { longitude: 104.9 },
        "阿坝藏族羌族自治州": { longitude: 102.2 },
        "甘孜藏族自治州": { longitude: 101.9 },
        "凉山彝族自治州": { longitude: 102.2 }
    },
    "贵州省": {
        "贵阳市": { longitude: 106.7 },
        "六盘水市": { longitude: 104.8 },
        "遵义市": { longitude: 106.9 },
        "安顺市": { longitude: 105.9 },
        "毕节市": { longitude: 105.2 },
        "铜仁市": { longitude: 109.1 },
        "黔东南苗族侗族自治州": { longitude: 107.9 },
        "黔南布依族苗族自治州": { longitude: 107.5 },
        "黔西南布依族苗族自治州": { longitude: 104.9 }
    },
    "云南省": {
        "昆明市": { longitude: 102.7 },
        "曲靖市": { longitude: 103.8 },
        "玉溪市": { longitude: 102.5 },
        "保山市": { longitude: 99.1 },
        "昭通市": { longitude: 103.7 },
        "丽江市": { longitude: 100.2 },
        "普洱市": { longitude: 101.0 },
        "临沧市": { longitude: 99.9 },
        "楚雄彝族自治州": { longitude: 101.5 },
        "红河哈尼族彝族自治州": { longitude: 103.4 },
        "文山壮族苗族自治州": { longitude: 104.2 },
        "西双版纳傣族自治州": { longitude: 100.8 },
        "大理白族自治州": { longitude: 100.2 },
        "德宏傣族景颇族自治州": { longitude: 98.6 },
        "怒江傈僳族自治州": { longitude: 98.8 },
        "迪庆藏族自治州": { longitude: 99.7 }
    },
    "西藏自治区": {
        "拉萨市": { longitude: 91.1 },
        "日喀则市": { longitude: 88.8 },
        "昌都市": { longitude: 97.1 },
        "林芝市": { longitude: 94.3 },
        "山南市": { longitude: 91.7 },
        "那曲市": { longitude: 92.0 },
        "阿里地区": { longitude: 80.1 }
    },
    "陕西省": {
        "西安市": { longitude: 108.9 },
        "铜川市": { longitude: 109.1 },
        "宝鸡市": { longitude: 107.1 },
        "咸阳市": { longitude: 108.7 },
        "渭南市": { longitude: 109.5 },
        "延安市": { longitude: 109.4 },
        "汉中市": { longitude: 107.0 },
        "榆林市": { longitude: 109.7 },
        "安康市": { longitude: 109.0 },
        "商洛市": { longitude: 110.0 }
    },
    "甘肃省": {
        "兰州市": { longitude: 103.7 },
        "嘉峪关市": { longitude: 98.2 },
        "金昌市": { longitude: 102.2 },
        "白银市": { longitude: 104.1 },
        "天水市": { longitude: 105.7 },
        "武威市": { longitude: 102.6 },
        "张掖市": { longitude: 100.4 },
        "平凉市": { longitude: 106.6 },
        "酒泉市": { longitude: 98.5 },
        "庆阳市": { longitude: 107.6 },
        "定西市": { longitude: 104.6 },
        "陇南市": { longitude: 104.9 },
        "临夏回族自治州": { longitude: 103.2 },
        "甘南藏族自治州": { longitude: 102.9 }
    },
    "青海省": {
        "西宁市": { longitude: 101.7 },
        "海东市": { longitude: 102.1 },
        "海北藏族自治州": { longitude: 100.9 },
        "黄南藏族自治州": { longitude: 102.0 },
        "海南藏族自治州": { longitude: 100.6 },
        "果洛藏族自治州": { longitude: 100.2 },
        "玉树藏族自治州": { longitude: 97.0 },
        "海西蒙古族藏族自治州": { longitude: 97.0 }
    },
    "宁夏回族自治区": {
        "银川市": { longitude: 106.2 },
        "石嘴山市": { longitude: 106.3 },
        "吴忠市": { longitude: 106.1 },
        "固原市": { longitude: 106.2 },
        "中卫市": { longitude: 105.1 }
    },
    "新疆维吾尔自治区": {
        "乌鲁木齐市": { longitude: 87.6 },
        "克拉玛依市": { longitude: 84.7 },
        "吐鲁番市": { longitude: 89.2 },
        "哈密市": { longitude: 93.5 },
        "昌吉回族自治州": { longitude: 87.3 },
        "博尔塔拉蒙古自治州": { longitude: 82.0 },
        "巴音郭楞蒙古自治州": { longitude: 86.1 },
        "阿克苏地区": { longitude: 80.3 },
        "克孜勒苏柯尔克孜自治州": { longitude: 76.2 },
        "喀什地区": { longitude: 75.9 },
        "和田地区": { longitude: 79.9 },
        "伊犁哈萨克自治州": { longitude: 81.3 },
        "塔城地区": { longitude: 82.9 },
        "阿勒泰地区": { longitude: 88.1 },
        "石河子市": { longitude: 86.0 },
        "阿拉尔市": { longitude: 81.2 },
        "图木舒克市": { longitude: 79.0 },
        "五家渠市": { longitude: 87.2 }
    },
    "香港特别行政区": { "香港": { longitude: 114.1 } },
    "澳门特别行政区": { "澳门": { longitude: 113.5 } },

};

const stems = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"];
const branches = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"];
const zodiac = ['鼠', '牛', '虎', '兔', '龍', '蛇', '馬', '羊', '猴', '雞', '狗', '豬'];
